In [26]:
import os
path=os.getcwd()

In [27]:
import glob
import pandas as pd

In [28]:
import pandas as pd
import glob
import os

# Folder containing CSV files
folder_path = path

# Get all CSV files
csv_files = glob.glob(os.path.join(folder_path, "*.csv"))

# Read and combine
df = pd.concat([pd.read_csv(file) for file in csv_files], ignore_index=True)

# Save the combined CSV
df.to_csv("Qwen_3.5_1.7B_Output.csv", index=False)

print(df.shape)

(75168, 5)

In [29]:
path

'/mnt/sda1/osint_intern/SA_Group/Raunak/Culture_Aware_Sentiment_Analysis/Implementation/Qwen/Qwen 3.5 1.7 B/state_results'

In [30]:
os.listdir()

['Puducherry.csv',
 '.ipynb_checkpoints',
 'Lakshadweep.csv',
 'Gujarat.csv',
 'Maharashtra.csv',
 'Goa.csv',
 'Rajasthan.csv',
 'Delhi.csv',
 'Haryana.csv',
 'Chandigarh.csv',
 'Himachal_Pradesh.csv',
 'Jammu_and_Kashmir.csv',
 'Karnataka.csv',
 'Kerala.csv',
 'Ladakh.csv',
 'Bihar_output.csv',
 'Tamil_Nadu.csv',
 'Punjab.csv',
 'Uttarakhand.csv',
 'Uttar_Pradesh.csv',
 'Dadra_and_Nagar_Haveli.csv',
 'Daman_and_Diu.csv',
 'West_Bengal.csv',
 'Odisha.csv',
 'Bihar.csv',
 'Jharkhand.csv',
 'Andaman_and_Nicobar.csv',
 'Madhya_Pradesh.csv',
 'Chhattisgarh.csv',
 'Assam.csv',
 'Arunachal_Pradesh.csv',
 'Manipur.csv',
 'Meghalaya.csv',
 'Mizoram.csv',
 'Nagaland.csv',
 'Sikkim.csv',
 'Tripura.csv',
 'Untitled.ipynb',
 'Qwen_3.5_1.7B_Output.csv']

In [31]:
tmp

                     State Sentiment Bihar_qwen_sentiment
42856  Andaman_and_Nicobar  positive                  NaN
17800  Andaman_and_Nicobar  positive                  NaN
45640    Arunachal_Pradesh  positive                  NaN
20584    Arunachal_Pradesh  positive                  NaN
44944                Assam  positive                  NaN
...                    ...       ...                  ...
13200        Uttar_Pradesh   neutral                  NaN
37560          Uttarakhand   neutral                  NaN
12504          Uttarakhand   neutral                  NaN
40344          West_Bengal   neutral                  NaN
15288          West_Bengal   neutral                  NaN

[48720 rows x 3 columns]

In [32]:
qwendf = (
    df.sort_values("State")
      .groupby(["Hindi", "Region", "State"], as_index=False)
      .first()                      # Remove duplicate rows for the same state
      .groupby(["Hindi", "Region"], group_keys=False)
      .head(3)                      # Keep at most 3 states per sentence per region
      [["Hindi", "Region", "State", "Sentiment"]]
      .reset_index(drop=True)
)

In [35]:
df

,Hindi,State,Region,Sentiment,Bihar_qwen_sentiment
0,कई नवविवाहित जोड़े शादी के बाद अपने विस्तारित ...,Puducherry,Puducherry - Southern Cultural Region,neutral,NaN
1,छात्र अक्सर अपने शिक्षक के चरणों को छूकर आशीर्...,Puducherry,Puducherry - Southern Cultural Region,neutral,NaN
2,उसे अपने परिवार की देखभाल के लिए अपनी नौकरी छो...,Puducherry,Puducherry - Southern Cultural Region,neutral,NaN
3,परिवार की ज़िम्मेदारियों के लिए करियर का त्याग...,Puducherry,Puducherry - Southern Cultural Region,neutral,NaN
4,महिलाओं से यह उम्मीद नहीं की जानी चाहिए कि वे ...,Puducherry,Puducherry - Southern Cultural Region,neutral,NaN
...,...,...,...,...,...
75163,"सजाए गए सलाद और सॉस के अलावा खीरे का रायता, नी...",Tripura,Tripura - Northeastern Cultural Region,neutral,NaN
75164,"कुमाऊँनी और गढ़वाली दोनों शैलियों में घी, दाल ...",Tripura,Tripura - Northeastern Cultural Region,neutral,NaN
75165,वे कभी-कभी सब्ज़ियों के विकल्प के रूप में बादी ...,Tripura,Tripura - Northeastern Cultural Region,positive,NaN
75166,उत्तराखंड के लोग त्योहारों और अन्य उत्सवों के ...,Tripura,Tripura - Northeastern Cultural Region,neutral,NaN
75167,"उत्तराखंड में सिंगोड़ी, बाल-मिठाई और मलाई लड्डू...",Tripura,Tripura - Northeastern Cultural Region,positive,NaN

In [36]:
tmp = (
    df.groupby(["Hindi", "Region"], group_keys=False)
      .apply(
          lambda g: g.drop_duplicates("State").sample(
              n=min(3, g["State"].nunique()),
              random_state=42
          )
      )
)

print(tmp.columns)
print(tmp.index.names)

Index(['State', 'Sentiment', 'Bihar_qwen_sentiment'], dtype='str')
[None]

In [37]:
tmp

                     State Sentiment Bihar_qwen_sentiment
17800  Andaman_and_Nicobar  positive                  NaN
20584    Arunachal_Pradesh  positive                  NaN
19888                Assam  positive                  NaN
16408                Bihar  positive                  NaN
5968            Chandigarh  positive                  NaN
...                    ...       ...                  ...
11112           Tamil_Nadu   neutral                  NaN
25032              Tripura   neutral                  NaN
13200        Uttar_Pradesh   neutral                  NaN
12504          Uttarakhand   neutral                  NaN
15288          West_Bengal   neutral                  NaN

[24360 rows x 3 columns]

In [38]:
tmp = tmp.reset_index()

print(tmp.columns)

Index(['index', 'State', 'Sentiment', 'Bihar_qwen_sentiment'], dtype='str')

In [39]:
tmp["index"]

0        17800
1        20584
2        19888
3        16408
4         5968
         ...
24355    11112
24356    25032
24357    13200
24358    12504
24359    15288
Name: index, Length: 24360, dtype: int64

In [40]:
tmp

       index                State Sentiment Bihar_qwen_sentiment
0      17800  Andaman_and_Nicobar  positive                  NaN
1      20584    Arunachal_Pradesh  positive                  NaN
2      19888                Assam  positive                  NaN
3      16408                Bihar  positive                  NaN
4       5968           Chandigarh  positive                  NaN
...      ...                  ...       ...                  ...
24355  11112           Tamil_Nadu   neutral                  NaN
24356  25032              Tripura   neutral                  NaN
24357  13200        Uttar_Pradesh   neutral                  NaN
24358  12504          Uttarakhand   neutral                  NaN
24359  15288          West_Bengal   neutral                  NaN

[24360 rows x 4 columns]

In [43]:
df

,Hindi,State,Region,Sentiment,Bihar_qwen_sentiment
0,कई नवविवाहित जोड़े शादी के बाद अपने विस्तारित ...,Puducherry,Puducherry - Southern Cultural Region,neutral,NaN
1,छात्र अक्सर अपने शिक्षक के चरणों को छूकर आशीर्...,Puducherry,Puducherry - Southern Cultural Region,neutral,NaN
2,उसे अपने परिवार की देखभाल के लिए अपनी नौकरी छो...,Puducherry,Puducherry - Southern Cultural Region,neutral,NaN
3,परिवार की ज़िम्मेदारियों के लिए करियर का त्याग...,Puducherry,Puducherry - Southern Cultural Region,neutral,NaN
4,महिलाओं से यह उम्मीद नहीं की जानी चाहिए कि वे ...,Puducherry,Puducherry - Southern Cultural Region,neutral,NaN
...,...,...,...,...,...
75163,"सजाए गए सलाद और सॉस के अलावा खीरे का रायता, नी...",Tripura,Tripura - Northeastern Cultural Region,neutral,NaN
75164,"कुमाऊँनी और गढ़वाली दोनों शैलियों में घी, दाल ...",Tripura,Tripura - Northeastern Cultural Region,neutral,NaN
75165,वे कभी-कभी सब्ज़ियों के विकल्प के रूप में बादी ...,Tripura,Tripura - Northeastern Cultural Region,positive,NaN
75166,उत्तराखंड के लोग त्योहारों और अन्य उत्सवों के ...,Tripura,Tripura - Northeastern Cultural Region,neutral,NaN
75167,"उत्तराखंड में सिंगोड़ी, बाल-मिठाई और मलाई लड्डू...",Tripura,Tripura - Northeastern Cultural Region,positive,NaN

In [45]:
import pandas as pd
print(pd.__version__)

3.0.3

In [46]:
import pandas as pd

rows = []

for (hindi, region), g in df.groupby(["Hindi", "Region"]):
    sample = (
        g.drop_duplicates(subset="State")
         .sample(n=min(3, g["State"].nunique()), random_state=42)
         .copy()
    )

    sample["Hindi"] = hindi
    sample["Region"] = region

    rows.append(sample)

qwendf = (
    pd.concat(rows, ignore_index=True)
      [["Hindi", "Region", "State", "Sentiment"]]
)

print(qwendf.head())

                                               Hindi  \
0  अंडमान और निकोबार द्वीप समूह के व्यंजनों में स...
1  अंडमान और निकोबार द्वीप समूह के व्यंजनों में स...
2  अंडमान और निकोबार द्वीप समूह के व्यंजनों में स...
3  अंडमान और निकोबार द्वीप समूह के व्यंजनों में स...
4  अंडमान और निकोबार द्वीप समूह के व्यंजनों में स...

                                              Region                State  \
0  Andaman and Nicobar Islands - Eastern Cultural...  Andaman_and_Nicobar
1   Arunachal Pradesh - Northeastern Cultural Region    Arunachal_Pradesh
2               Assam - Northeastern Cultural Region                Assam
3                    Bihar - Eastern Cultural Region                Bihar
4              Chandigarh - Northern Cultural Region           Chandigarh

  Sentiment
0  positive
1  positive
2  positive
3  positive
4  positive

In [52]:

qwendf["Region"] = qwendf["Region"].str.replace(
    r"^.*? - ",
    "",
    regex=True
)

In [53]:
qwendf

,Hindi,Region,State,Sentiment
0,अंडमान और निकोबार द्वीप समूह के व्यंजनों में स...,Eastern Cultural Region,Andaman_and_Nicobar,positive
1,अंडमान और निकोबार द्वीप समूह के व्यंजनों में स...,Northeastern Cultural Region,Arunachal_Pradesh,positive
2,अंडमान और निकोबार द्वीप समूह के व्यंजनों में स...,Northeastern Cultural Region,Assam,positive
3,अंडमान और निकोबार द्वीप समूह के व्यंजनों में स...,Eastern Cultural Region,Bihar,positive
4,अंडमान और निकोबार द्वीप समूह के व्यंजनों में स...,Northern Cultural Region,Chandigarh,positive
...,...,...,...,...
24355,"हैदराबादी व्यंजनों में बिरयानी, हलीम, बघारा बै...",Southern Cultural Region,Tamil_Nadu,neutral
24356,"हैदराबादी व्यंजनों में बिरयानी, हलीम, बघारा बै...",Northeastern Cultural Region,Tripura,neutral
24357,"हैदराबादी व्यंजनों में बिरयानी, हलीम, बघारा बै...",Northern Cultural Region,Uttar_Pradesh,neutral
24358,"हैदराबादी व्यंजनों में बिरयानी, हलीम, बघारा बै...",Northern Cultural Region,Uttarakhand,neutral
24359,"हैदराबादी व्यंजनों में बिरयानी, हलीम, बघारा बै...",Eastern Cultural Region,West_Bengal,neutral

In [56]:
qwendf.head(20)

,Hindi,Region,State,Sentiment
0,अंडमान और निकोबार द्वीप समूह के व्यंजनों में स...,Eastern Cultural Region,Andaman_and_Nicobar,positive
1,अंडमान और निकोबार द्वीप समूह के व्यंजनों में स...,Northeastern Cultural Region,Arunachal_Pradesh,positive
2,अंडमान और निकोबार द्वीप समूह के व्यंजनों में स...,Northeastern Cultural Region,Assam,positive
3,अंडमान और निकोबार द्वीप समूह के व्यंजनों में स...,Eastern Cultural Region,Bihar,positive
4,अंडमान और निकोबार द्वीप समूह के व्यंजनों में स...,Northern Cultural Region,Chandigarh,positive
5,अंडमान और निकोबार द्वीप समूह के व्यंजनों में स...,Central Cultural Region,Chhattisgarh,positive
6,अंडमान और निकोबार द्वीप समूह के व्यंजनों में स...,Western Cultural Region,Dadra_and_Nagar_Haveli,positive
7,अंडमान और निकोबार द्वीप समूह के व्यंजनों में स...,Western Cultural Region,Daman_and_Diu,positive
8,अंडमान और निकोबार द्वीप समूह के व्यंजनों में स...,Northern Cultural Region,Delhi,positive
9,अंडमान और निकोबार द्वीप समूह के व्यंजनों में स...,Western Cultural Region,Goa,positive
10,अंडमान और निकोबार द्वीप समूह के व्यंजनों में स...,Western Cultural Region,Gujarat,positive
11,अंडमान और निकोबार द्वीप समूह के व्यंजनों में स...,Northern Cultural Region,Haryana,positive
12,अंडमान और निकोबार द्वीप समूह के व्यंजनों में स...,Northern Cultural Region,Himachal_Pradesh,positive
13,अंडमान और निकोबार द्वीप समूह के व्यंजनों में स...,Northern Cultural Region,Jammu_and_Kashmir,positive
14,अंडमान और निकोबार द्वीप समूह के व्यंजनों में स...,Eastern Cultural Region,Jharkhand,positive
15,अंडमान और निकोबार द्वीप समूह के व्यंजनों में स...,Southern Cultural Region,Karnataka,positive
16,अंडमान और निकोबार द्वीप समूह के व्यंजनों में स...,Southern Cultural Region,Kerala,positive
17,अंडमान और निकोबार द्वीप समूह के व्यंजनों में स...,Northern Cultural Region,Ladakh,positive
18,अंडमान और निकोबार द्वीप समूह के व्यंजनों में स...,Southern Cultural Region,Lakshadweep,positive
19,अंडमान और निकोबार द्वीप समूह के व्यंजनों में स...,Central Cultural Region,Madhya_Pradesh,positive

In [57]:
qwendf = (
    qwendf
    .sort_values(by=["Hindi", "Region"], kind="stable")
    .reset_index(drop=True)
)

In [59]:
qwendf.head(20)

,Hindi,Region,State,Sentiment
0,अंडमान और निकोबार द्वीप समूह के व्यंजनों में स...,Central Cultural Region,Chhattisgarh,positive
1,अंडमान और निकोबार द्वीप समूह के व्यंजनों में स...,Central Cultural Region,Madhya_Pradesh,positive
2,अंडमान और निकोबार द्वीप समूह के व्यंजनों में स...,Eastern Cultural Region,Andaman_and_Nicobar,positive
3,अंडमान और निकोबार द्वीप समूह के व्यंजनों में स...,Eastern Cultural Region,Bihar,positive
4,अंडमान और निकोबार द्वीप समूह के व्यंजनों में स...,Eastern Cultural Region,Jharkhand,positive
5,अंडमान और निकोबार द्वीप समूह के व्यंजनों में स...,Eastern Cultural Region,Odisha,positive
6,अंडमान और निकोबार द्वीप समूह के व्यंजनों में स...,Eastern Cultural Region,West_Bengal,positive
7,अंडमान और निकोबार द्वीप समूह के व्यंजनों में स...,Northeastern Cultural Region,Arunachal_Pradesh,positive
8,अंडमान और निकोबार द्वीप समूह के व्यंजनों में स...,Northeastern Cultural Region,Assam,positive
9,अंडमान और निकोबार द्वीप समूह के व्यंजनों में स...,Northeastern Cultural Region,Manipur,positive
10,अंडमान और निकोबार द्वीप समूह के व्यंजनों में स...,Northeastern Cultural Region,Meghalaya,positive
11,अंडमान और निकोबार द्वीप समूह के व्यंजनों में स...,Northeastern Cultural Region,Mizoram,positive
12,अंडमान और निकोबार द्वीप समूह के व्यंजनों में स...,Northeastern Cultural Region,Nagaland,positive
13,अंडमान और निकोबार द्वीप समूह के व्यंजनों में स...,Northeastern Cultural Region,Sikkim,positive
14,अंडमान और निकोबार द्वीप समूह के व्यंजनों में स...,Northeastern Cultural Region,Tripura,positive
15,अंडमान और निकोबार द्वीप समूह के व्यंजनों में स...,Northern Cultural Region,Chandigarh,positive
16,अंडमान और निकोबार द्वीप समूह के व्यंजनों में स...,Northern Cultural Region,Delhi,positive
17,अंडमान और निकोबार द्वीप समूह के व्यंजनों में स...,Northern Cultural Region,Haryana,positive
18,अंडमान और निकोबार द्वीप समूह के व्यंजनों में स...,Northern Cultural Region,Himachal_Pradesh,positive
19,अंडमान और निकोबार द्वीप समूह के व्यंजनों में स...,Northern Cultural Region,Jammu_and_Kashmir,positive

In [60]:
696*36

25056

In [62]:
qwendf.to_csv("qwendf.csv", index=False, encoding="utf-8-sig")

In [ ]:
qw

In [ ]:
qwendf now selects all states it should select at max three sates from each region randomly

In [63]:
qwendf.tail()

,Hindi,Region,State,Sentiment
24355,"हैदराबादी व्यंजनों में बिरयानी, हलीम, बघारा बै...",Western Cultural Region,Daman_and_Diu,neutral
24356,"हैदराबादी व्यंजनों में बिरयानी, हलीम, बघारा बै...",Western Cultural Region,Goa,neutral
24357,"हैदराबादी व्यंजनों में बिरयानी, हलीम, बघारा बै...",Western Cultural Region,Gujarat,neutral
24358,"हैदराबादी व्यंजनों में बिरयानी, हलीम, बघारा बै...",Western Cultural Region,Maharashtra,neutral
24359,"हैदराबादी व्यंजनों में बिरयानी, हलीम, बघारा बै...",Western Cultural Region,Rajasthan,neutral

In [64]:
import pandas as pd

# Randomly select at most 3 states from each region
selected_states = (
    qwendf.groupby("Region")["State"]
           .apply(lambda s: s.drop_duplicates().sample(
               n=min(3, s.nunique()),
               random_state=42
           ).tolist())
           .to_dict()
)

# Filter qwendf
qwen_output_df = qwendf[
    qwendf.apply(
        lambda row: row["State"] in selected_states[row["Region"]],
        axis=1
    )
].reset_index(drop=True)

# Keep only the required columns
qwen_output_df = qwen_output_df[
    ["Hindi", "Region", "State", "Sentiment"]
]

In [65]:
# Keep only the required columns
qwen_output_df

,Hindi,Region,State,Sentiment
0,अंडमान और निकोबार द्वीप समूह के व्यंजनों में स...,Central Cultural Region,Chhattisgarh,positive
1,अंडमान और निकोबार द्वीप समूह के व्यंजनों में स...,Central Cultural Region,Madhya_Pradesh,positive
2,अंडमान और निकोबार द्वीप समूह के व्यंजनों में स...,Eastern Cultural Region,Bihar,positive
3,अंडमान और निकोबार द्वीप समूह के व्यंजनों में स...,Eastern Cultural Region,Jharkhand,positive
4,अंडमान और निकोबार द्वीप समूह के व्यंजनों में स...,Eastern Cultural Region,West_Bengal,positive
...,...,...,...,...
11827,"हैदराबादी व्यंजनों में बिरयानी, हलीम, बघारा बै...",Southern Cultural Region,Lakshadweep,neutral
11828,"हैदराबादी व्यंजनों में बिरयानी, हलीम, बघारा बै...",Southern Cultural Region,Tamil_Nadu,neutral
11829,"हैदराबादी व्यंजनों में बिरयानी, हलीम, बघारा बै...",Western Cultural Region,Dadra_and_Nagar_Haveli,neutral
11830,"हैदराबादी व्यंजनों में बिरयानी, हलीम, बघारा बै...",Western Cultural Region,Daman_and_Diu,neutral
11831,"हैदराबादी व्यंजनों में बिरयानी, हलीम, बघारा बै...",Western Cultural Region,Rajasthan,neutral

In [67]:
# Keep only the required columns
qwen_output_df.to_csv("Qwen_3.5_1B_output.csv", index=False, encoding="utf-8-sig")

In [68]:
os.listdir()

['Puducherry.csv',
 '.ipynb_checkpoints',
 'Lakshadweep.csv',
 'Gujarat.csv',
 'Maharashtra.csv',
 'Goa.csv',
 'Rajasthan.csv',
 'Delhi.csv',
 'Haryana.csv',
 'Chandigarh.csv',
 'Himachal_Pradesh.csv',
 'Jammu_and_Kashmir.csv',
 'Karnataka.csv',
 'Kerala.csv',
 'Ladakh.csv',
 'Bihar_output.csv',
 'Tamil_Nadu.csv',
 'Punjab.csv',
 'Uttarakhand.csv',
 'Uttar_Pradesh.csv',
 'Dadra_and_Nagar_Haveli.csv',
 'Daman_and_Diu.csv',
 'West_Bengal.csv',
 'Odisha.csv',
 'Bihar.csv',
 'Jharkhand.csv',
 'Andaman_and_Nicobar.csv',
 'Madhya_Pradesh.csv',
 'Chhattisgarh.csv',
 'Assam.csv',
 'Arunachal_Pradesh.csv',
 'Manipur.csv',
 'Meghalaya.csv',
 'Mizoram.csv',
 'Nagaland.csv',
 'Sikkim.csv',
 'Tripura.csv',
 'Untitled.ipynb',
 'Qwen_3.5_1.7B_Output.csv',
 'qwendf.csv',
 'Qwen_3.5_1B_output.csv']

In [69]:
os.listdir()
os.getcwd()

'/mnt/sda1/osint_intern/SA_Group/Raunak/Culture_Aware_Sentiment_Analysis/Implementation/Qwen/Qwen 3.5 1.7 B/state_results'